### ISSUE TITLE
Using idalib

### ISSUE THREAD

**Issue by doronz88** [DennyDai/headless-ida#11]
Hi!

Thanks for this amazing project!
Can I supply `idalib` from the CLI? Or is it only IDA executables?

**Comment by DennyDai** [comment]
Yes it does! just do `headless-ida /path/to/ida9/libidalib64.so /path/to/binary /path/to/your_ida_script.py`, I forgot to push the update to PyPI but now it should be available and you can just update it with `pip install -U headless-ida`
