### ISSUE TITLE
Decompilation failed: ffffffffffffffff

### ISSUE THREAD

**Issue by rezaapjafari** [DennyDai/headless-ida#5]
HI there hope you are doing well

i wan to decomplie functions but i get error "Decompilation failed: ffffffffffffffff".
i run the same script in IDA PRO and it works, but it does not work with headless ida.

Thanks

**Comment by DennyDai** [comment]
Could you provide the script you're using and the binary you're attempting to decompile? Having more details will help identify the issue

**Comment by rezaapjafari** [comment]
my Bad, I was trying to decompile 32bit with idat64
