### ISSUE TITLE
Support for pre-existing databases

### ISSUE THREAD

**Issue by Yakov5776** [DennyDai/headless-ida#6]
This seems to require loading a binary directly into IDA, I am making this assumption based off the mandatory -o and -P+ flags.

Is there a way to just load an existing database, query information off it, and do not flush database content to disk?
Additionally, is there a way to initialize HeadlessIda without passing any binary paths provided there's a server running and we know the port?

Thank you!

**Comment by DennyDai** [comment]
> Is there a way to just load an existing database, query information off it, and do not flush database content to disk?
No currently there is no way to do this, but I can add this maybe next week as it seems to be a pretty useful feature.

> is there a way to initialize HeadlessIda without passing any binary paths provided there's a server running and we know the port
Yes, check `Advanced Usage` part in the README

**Comment by Yakov5776** [comment]
> No currently there is no way to do this, but I can add this maybe next week as it seems to be a pretty useful feature.

Looking forward 👀
> Yes, check `Advanced Usage` part in the README

I've seen that although I am unaware why this requires the path to IDA's executable.

**Comment by DennyDai** [comment]
> I've seen that although I am unsure why this requires the path to IDA's executable, is there something I am overlooking?

This tool is literally just a wrapper over ida as you must have already known, without ida it can't do any reverse engineering for you. And sure you don't have to specify the binary to be analyzed, you only need to do that when your CLIENT connects to it.

I feel there might be some misunderstanding in the readme, if you feel there is a better way to phrase it I can surely update it :)

**Comment by Yakov5776** [comment]
I see, I was under the assumption that the server was already launched with an executable.

**Comment by DennyDai** [comment]
> If we offer `Advanced Usage`, shouldn't we give the capability to the user to additionally connect without specifying an executable in this scenario?

I don't feel this will be useful to anyone, if a user don't have a binary to analyze yet, they just don't need to connect to server. (Server will be always there, user can disconnect and reconnect anytime). 

But if you do have a scenario in mind, please provide more details about it.

**Comment by Yakov5776** [comment]
>(Server will be always there, user can disconnect and reconnect anytime).

You've mentioned a client could disconnect and reconnect at anytime; is there a reason we need to be specifying the executable each time?

**Comment by DennyDai** [comment]
> You've mentioned a client could disconnect and reconnect at anytime; is there a reason we need to be specifying the executable each time?

I definitely should explain more on the readme I'm just bad at explaining things l guess.

Actually the binary will be gone once you disconnect. Every time a user connects, the tool will run a fresh ida instance, nothing will be persistent across different connections except the server itself.

**Comment by Yakov5776** [comment]
> Actually the binary will be gone once you disconnect. Every time a user connects, the tool will run a fresh ida instance, nothing will be persistent across different connections except the server itself.

I see, I guess there are use cases for both approaches.

would be nice to see the possibility of a persistent server, but as we discussed earlier, even loading a pre-existing database would be a nice feature.

Thank you!

**Comment by DennyDai** [comment]
Surely that load pre-existing features will be available on both local and server setup.

For the persistent server (user connects to the already opened ida instance) I guess I will not do it at least for now, which will make things lots easier. Humans are bad at remembering cleaning things up like remembering to close their remote ida instance after use.

**Comment by DennyDai** [comment]
Now you can load idb, just pass idb path instead of binary patch when loading.
No change will be write back to the idb you've opened unless you use `ida_loader.save_database("/path/to/db.idb")` to overwrite.
