### ISSUE TITLE
read .pdb file beside exe file

### ISSUE THREAD

**Issue by RzDJafari** [DennyDai/headless-ida#7]
Hi there i hope you are doing well
is there a way that i can read .pdb file beside .exe file?

**Comment by DennyDai** [comment]
I checked IDAPython API docs and also ida command line args but didn't find anyway to manually specify a pdb file path, let me know if you know other methods that works.

**Comment by RzDJafari** [comment]
i did not find either, but i found that if you put .exe file and .pdb file in the same folder that was initially compiled, ida reads them automatically.

**Comment by DennyDai** [comment]
Will headless ida load it automatically too? If so then I will mark this as resolved

**Comment by RzDJafari** [comment]
Yes, headless ida loads it automatically.
