### ISSUE TITLE
Has some way to load python3 plugin in headless-ida?

### ISSUE THREAD

**Issue by geemion** [DennyDai/headless-ida#8]
I want to use headless-ida to auto load a file, then exec ida pro python3 plugin 
i find “idaapi.load_and_run_plugin” can load C/C++ plugin but cann't load python3 script plugin

**Comment by DennyDai** [comment]
Could you provide more information about what happens when you load a Python 3 plugin?

**Comment by geemion** [comment]
I want use headless-ida to run https://github.com/polymorf/findcrypt-yara
How to to run the python3 plugin findcrypt3，if not modify the findcrypt3 plugin

**Comment by DennyDai** [comment]
The plugin was successfully loaded and run, but there was an issue with stdout not being forwarded back to the client. This has been resolved in version 0.5.3 :)
